language: node_js

node_js:
  - 10

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm prune
  - npm audit fix

script:

after_success:
  #- npm run semantic-release

