########################################################
# Development build                                    #
########################################################
FROM guyaltd/chat:build  AS development

ENV WORK_DIR /usr/src/app
WORKDIR ${WORK_DIR}

COPY . ./

CMD npm start

EXPOSE 3000


