########################################################
# Development build                                    #
########################################################
FROM node:13.12.0-alpine  AS development

ENV WORK_DIR /usr/src/app
WORKDIR ${WORK_DIR}

COPY . ./

CMD npm start

EXPOSE 3000


