########################################################
# Base                                                 #
########################################################
FROM node:13.12.0-alpine as build

ENV WORK_DIR /usr/src/app
WORKDIR ${WORK_DIR}

ENV PATH ${WORK_DIR}/node_modules/.bin:$PATH

COPY package.json .
#COPY package-lock.json .

RUN npm install

CMD npm run start:watch